// Generated by gencpp from file task1/IRStamped.msg
// DO NOT EDIT!


#ifndef TASK1_MESSAGE_IRSTAMPED_H
#define TASK1_MESSAGE_IRSTAMPED_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace task1
{
template <class ContainerAllocator>
struct IRStamped_
{
  typedef IRStamped_<ContainerAllocator> Type;

  IRStamped_()
    : header()
    , beam_index(0)  {
    }
  IRStamped_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , beam_index(0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef int32_t _beam_index_type;
  _beam_index_type beam_index;





  typedef boost::shared_ptr< ::task1::IRStamped_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::task1::IRStamped_<ContainerAllocator> const> ConstPtr;

}; // struct IRStamped_

typedef ::task1::IRStamped_<std::allocator<void> > IRStamped;

typedef boost::shared_ptr< ::task1::IRStamped > IRStampedPtr;
typedef boost::shared_ptr< ::task1::IRStamped const> IRStampedConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::task1::IRStamped_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::task1::IRStamped_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::task1::IRStamped_<ContainerAllocator1> & lhs, const ::task1::IRStamped_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.beam_index == rhs.beam_index;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::task1::IRStamped_<ContainerAllocator1> & lhs, const ::task1::IRStamped_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace task1

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::task1::IRStamped_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::task1::IRStamped_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::task1::IRStamped_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::task1::IRStamped_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::task1::IRStamped_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::task1::IRStamped_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::task1::IRStamped_<ContainerAllocator> >
{
  static const char* value()
  {
    return "2833188b873a5f2c26a8d59d0288053a";
  }

  static const char* value(const ::task1::IRStamped_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x2833188b873a5f2cULL;
  static const uint64_t static_value2 = 0x26a8d59d0288053aULL;
};

template<class ContainerAllocator>
struct DataType< ::task1::IRStamped_<ContainerAllocator> >
{
  static const char* value()
  {
    return "task1/IRStamped";
  }

  static const char* value(const ::task1::IRStamped_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::task1::IRStamped_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"int32 beam_index\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::task1::IRStamped_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::task1::IRStamped_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.beam_index);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct IRStamped_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::task1::IRStamped_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::task1::IRStamped_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "beam_index: ";
    Printer<int32_t>::stream(s, indent + "  ", v.beam_index);
  }
};

} // namespace message_operations
} // namespace ros

#endif // TASK1_MESSAGE_IRSTAMPED_H
